#!/bin/bash
set -xeuo pipefail
basedir=$(cd $(dirname $0) && pwd)
build=centos-continuous
buildscriptsdir=$(cd sig-atomic-buildscripts && pwd)
ref=centos-atomic-host/7/x86_64/devel/continuous

. ${basedir}/libtoolbox.sh
. ~/rsync-password.sh 

prepare_image_build installer
sudo rpm-ostree-toolbox installer ${toolbox_base_args} -o ${version} --overwrite
finish_image_build installer
