#!/bin/bash
set -xeuo pipefail
basedir=$(cd $(dirname $0) && pwd)
build=centos-continuous
buildscriptsdir=$(cd sig-atomic-buildscripts && pwd)
ref=centos-atomic-host/7/x86_64/devel/continuous

. ${basedir}/libtoolbox.sh
. ~/rsync-password.sh 

prepare_image_build cloud
# FIXME - use ISO content rather than KS
sudo rpm-ostree-toolbox imagefactory ${toolbox_base_args} -i kvm --preserve-ks-url \
     --tdl ${buildscriptsdir}/cahc.tdl \
     -k ${buildscriptsdir}/cloud.ks \
     -o ${version} --overwrite
finish_image_build cloud
