#!/bin/bash
set -xeuo pipefail
basedir=$(cd $(dirname $0) && pwd)
build=centos-continuous
buildscriptsdir=$(cd sig-atomic-buildscripts && pwd)
ref=centos-atomic-host/7/x86_64/devel/continuous

. ~/rsync-password.sh 

mkdir -p ${build}/images/logs
cd ${build}/images/

# Ensure we're operating on a clean base
(cd ${buildscriptsdir} && git clean -dfx && git reset --hard HEAD)

sudo rm installer* -rf

if ! test -d repo; then
    ostree --repo=repo init --mode=archive-z2
fi
ostree --repo=repo remote delete centos-atomic-continuous || true
ostree --repo=repo remote add --set=gpg-verify=false centos-atomic-continuous http://artifacts.ci.centos.org/sig-atomic/rdgo/centos-continuous/ostree/repo/
ostree --repo=repo pull --mirror --disable-fsync --depth=0 centos-atomic-continuous ${ref}

rev=$(ostree --repo=repo rev-parse ${ref})
version=$(ostree --repo=repo show --print-metadata-key=version ${ref} | sed -e "s,',,g")
# Work around https://lists.centos.org/pipermail/ci-users/2016-July/000302.html
for file in config.ini atomic-centos-continuous.repo; do
    sed -i -e 's,https://ci.centos.org/artifacts/,http://artifacts.ci.centos.org/,g' ${buildscriptsdir}/${file}
done
sudo rpm-ostree-toolbox installer -c ${buildscriptsdir}/config.ini -o installer-${version} --overwrite
sudo chown -R -h $USER:$USER installer-${version}
mv installer-${version}/logs logs/installer
mv installer-${version}/images installer

for v in installer; do
    rsync --delete --delete-after --stats -Hrlpt ${v}/ sig-atomic@artifacts.ci.centos.org::sig-atomic/${build}/images/${v}/
done
