#!/bin/bash
set -xeuo pipefail
refprefix=centos-atomic-host/7/x86_64/devel
basedir=$(cd $(dirname $0) && pwd)
. ${basedir}/libtask.sh
. ${basedir}/libtoolbox.sh

for v in ostree; do
    rsync --delete --stats -a sig-atomic@artifacts.ci.centos.org::sig-atomic/${build}/${v}/ ${v}/
done

# Update release tags
~/ostree-releng-scripts/do-release-tags --autocreate --repo=ostree/repo --releases=${buildscriptsdir}/releases.yml
smoketested_commit=$(ostree --repo=ostree/repo rev-parse ${refprefix}/smoketested)
# Reset alpha to the latest smoketested; see https://github.com/CentOS/sig-atomic-buildscripts/issues/269
ostree --repo=ostree/repo reset ${refprefix}/alpha ${refprefix}/smoketested
# Generate a delta for smoketested
if ostree --repo=ostree/repo rev-parse ${refprefix}/smoketested^ 2>/dev/null; then
    ostree --repo=ostree/repo static-delta generate -n ${refprefix}/smoketested
fi

treefile=centos-atomic-host-continuous.json
# Work around https://lists.centos.org/pipermail/ci-users/2016-July/000302.html
sed -i -e 's,https://ci.centos.org/artifacts/,http://artifacts.ci.centos.org/,g' ${buildscriptsdir}/atomic-centos-continuous.repo
sudo rpm-ostree compose tree --touch-if-changed=${BUILD_LOGS}/changed.stamp --repo=ostree/repo ${buildscriptsdir}/${treefile}
if test -f ${BUILD_LOGS}/changed.stamp; then
    sudo chown -R -h $USER:$USER ostree/repo
    ostree --repo=ostree/repo summary -u
    rpm-ostree db --repo=ostree/repo diff centos-atomic-host/7/x86_64/devel/continuous{^,}
    ostree --repo=ostree/repo static-delta generate centos-atomic-host/7/x86_64/devel/continuous
    ostree --repo=ostree/repo prune --retain-branch-depth=centos-atomic-host/7/x86_64/devel/smoketested=5 --keep-younger-than='30 days ago' --refs-only
fi

# Always regenerate this right now since otherwise we have to track
# potential changes from anything above.
ostree --repo=ostree/repo summary -u

for v in ostree; do
    sudo chown -R -h $USER:$USER ${v}/
    find ${v}/ ! -type l -exec chmod a+rX {} +
    rsync --delete --stats -a ${v}/ sig-atomic@artifacts.ci.centos.org::sig-atomic/${build}/${v}/
done
