#!/bin/bash
set -xeuo pipefail

basedir=$(cd $(dirname $0) && pwd)

. ~/rsync-password.sh 

build=centos-continuous

mkdir -p ${build}
origdir=$(pwd)
cd ${build}
for v in rdgo ostree; do
    rsync --stats -av sig-atomic@artifacts.ci.centos.org::sig-atomic/${build}/${v} .
done

build_success=false
if ${basedir}/run-build ${origdir}; then
    build_success=true
fi

for v in rdgo ostree; do
    rsync --stats -av ${v} sig-atomic@artifacts.ci.centos.org::sig-atomic/${build}/${v}
done
if test "${build_success}" = false; then
    echo "Build failed, see logs above"; exit 1
fi
