#!/bin/bash
set -xeuo pipefail

basedir=$(cd $(dirname $0) && pwd)
. ${basedir}/libtask.sh

cd rdgo
# Note this needs to point inside the container paths
ln -sf /srv/src/overlay.yml .
if ! test -d src; then
    run_assembler rpmdistro-gitoverlay init
fi

# Git fetch all the things
run_assembler ls -al
run_assembler rpmdistro-gitoverlay resolve --fetch-all
# Do a build
run_assembler rpmdistro-gitoverlay build --touch-if-changed /srv/tmp/changed.stamp --logdir=/srv/home/build-logs
