#!/bin/bash
set -xeuo pipefail
basedir=$(cd $(dirname $0) && pwd)
. ${basedir}/libtask.sh
. ${basedir}/libtoolbox.sh

for v in ostree; do
    rsync --delete --stats -a sig-atomic@artifacts.ci.centos.org::sig-atomic/${build}/${v}/ ${v}/
done

# Update release tags
$basedir/do-release-tags --ignore-no-previous-promotion --repo=ostree/repo --releases=${buildscriptsdir}/releases.yml
# Ensure we have a delta from the previous alpha
ostree --repo=ostree/repo static-delta generate -n --from=59ba6b05b53c53df47e7c043d37f6d68ef643fc6a23c091797e6a7de707bce90 --to=centos-atomic-host/7/x86_64/devel/alpha
# Now, ensure we have a delta from N-1 -> N
ostree --repo=ostree/repo static-delta generate -n centos-atomic-host/7/x86_64/devel/alpha

treefile=centos-atomic-host-continuous.json
# Work around https://lists.centos.org/pipermail/ci-users/2016-July/000302.html
sed -i -e 's,https://ci.centos.org/artifacts/,http://artifacts.ci.centos.org/,g' ${buildscriptsdir}/atomic-centos-continuous.repo
sudo rpm-ostree compose tree --touch-if-changed=${WORKSPACE}/treecompose.stamp --repo=ostree/repo ${buildscriptsdir}/${treefile}
if test -f ${WORKSPACE}/treecompose.stamp; then
    sudo chown -R -h $USER:$USER ostree/repo
    ostree --repo=ostree/repo summary -u
    rpm-ostree db --repo=ostree/repo diff centos-atomic-host/7/x86_64/devel/continuous{^,}
    ostree --repo=ostree/repo static-delta generate centos-atomic-host/7/x86_64/devel/continuous
    ostree --repo=ostree/repo prune --keep-younger-than='30 days ago' --refs-only
fi

# Always regenerate this right now since otherwise we have to track
# potential changes from anything above.
ostree --repo=ostree/repo summary -u

for v in ostree; do
    rsync --delete --stats -a ${v}/ sig-atomic@artifacts.ci.centos.org::sig-atomic/${build}/${v}/
done
