#!/bin/bash
set -xeuo pipefail
basedir=$(cd $(dirname $0) && pwd)
. ${basedir}/libtask.sh
. ${basedir}/libtoolbox.sh

prepare_image_build installer
sudo rpm-ostree-toolbox installer ${toolbox_base_args} -o ${version} --overwrite
finish_image_build installer
