#!/bin/bash
set -xeuo pipefail

basedir=$(cd $(dirname $0) && pwd)
. ${basedir}/libtask.sh

cd rdgo
ln -sf ${buildscriptsdir}/overlay.yml .
if ! test -d src; then
    rpmdistro-gitoverlay init
fi

# Git fetch all the things
rpmdistro-gitoverlay resolve --fetch-all
# Do a build
rpmdistro-gitoverlay build --touch-if-changed ${BUILD_LOGS}/changed.stamp --logdir=${BUILD_LOGS}
