#!/bin/bash
set -xeuo pipefail
basedir=$(cd $(dirname $0) && pwd)
. ${basedir}/libtask.sh
. ${basedir}/libtoolbox.sh

prepare_image_build pxelive
sudo rpm-ostree-toolbox liveimage ${toolbox_base_args} --preserve-ks-url \
     --tdl ${buildscriptsdir}/cahc.tdl \
     -k ${buildscriptsdir}/pxelive.ks \
     -o ${version} --overwrite
finish_image_build pxelive
