#!/bin/bash
set -xeuo pipefail
basedir=$(cd $(dirname $0) && pwd)
. ${basedir}/libtask.sh
. ${basedir}/libtoolbox.sh

prepare_image_build cloud

copy_ppms() {
    find /var/lib/oz/screenshots -name '*.ppm' | xargs -r -I{} cp {} $BUILD_LOGS
}
trap copy_ppms ERR

# override oz config to at least 3G
# FIXME - this should probably be an rpm-ostree-toolbox setting
sudo sed -i 's/ *# *memory *= */memory = /' /etc/oz/oz.cfg # uncomment first
sudo sed -i 's/memory = .*/memory = 3072/' /etc/oz/oz.cfg

# FIXME - use ISO content rather than KS
sudo rpm-ostree-toolbox imagefactory ${toolbox_base_args} -i kvm -i vagrant-libvirt -i vagrant-virtualbox --preserve-ks-url \
     --tdl ${buildscriptsdir}/cahc.tdl \
     -k ${buildscriptsdir}/cloud.ks \
     --vkickstart ${buildscriptsdir}/vagrant.ks \
     -o ${version} --overwrite

finish_image_build cloud
