#!/bin/bash
set -xeuo pipefail

basedir=$(cd $(dirname $0) && pwd)
. ${basedir}/libtask.sh
. ${basedir}/libvm.sh

# In this workflow, we just assume that there is a new commit to test (we're
# triggered only when a new tree is composed). Otherwise, we'll have to figure
# out where to keep some state.

git clone https://github.com/projectatomic/atomic-host-tests

domain=$(uuidgen | cut -f1 -d-)
qcow2=/var/lib/libvirt/images/$domain.qcow2

# use http rather than https because:
# https://lists.centos.org/pipermail/ci-users/2016-July/000301.html
sudo curl -Lo $qcow2.gz \
    http://artifacts.ci.centos.org/sig-atomic/centos-continuous/images/cloud/latest/images/centos-atomic-host-7.qcow2.gz
sudo gunzip $qcow2.gz

$utils/create-vm $domain $qcow2
ip=$($utils/get-vm-ip $domain)
vm_setup $ip

# use http rather than https (just in case) because:
# https://lists.centos.org/pipermail/ci-users/2016-July/000301.html
vm_cmd sed -i -e 's,https://ci.centos.org/artifacts/,http://artifacts.ci.centos.org/,g' \
    /etc/ostree/remotes.d/centos-atomic-continuous.conf
head=$(vm_cmd ostree rev-parse centos-atomic-host/7/x86_64/devel/continuous)

export ANSIBLE_HOST_KEY_CHECKING=False

# The 'smoketest' job was failing while trying to copy files from the host
# under test to the host running Ansible.  The following error was observed:
#
#   Authentication or permission failure. In some cases, you may have been
#   able to authenticate and did not have permissions on the target directory.
#   Consider changing the remote tmp path in ansible.cfg to a path rooted
#   in "/tmp". Failed command was: ( umask 77 &&
#   mkdir -p "` echo /root/.ansible/tmp/ansible-tmp-1527796579.81-233460530664079 `" &&
#   echo ansible-tmp-1527796579.81-233460530664079="`
#   echo /root/.ansible/tmp/ansible-tmp-1527796579.81-233460530664079 `" ),
#   exited with result 1
#
# Unfortunately, there doesn't seem to be an environment variable to configure
# the remote temp directory, so we'll create an `ansible.cfg` file to use
# for the sanity test.  As long as it lives in the current directory,
# Ansible should pick it up and use it.
#
# https://davesnigier.com/changing-ansible-temporary-directory/
cat <<EOF > ./ansible.cfg
remote_tmp = /tmp/.ansible-${USER}/tmp/
EOF

pass=0
if ansible-playbook -v -i $ip, -u root \
    atomic-host-tests/tests/improved-sanity-test/main.yml; then
        pass=1
fi

if [ $pass = 0 ]; then
    echo "Test failed. See above for output."
    exit 1
else
    echo "Test passed."
    touch ${BUILD_LOGS}/changed.stamp
    echo "$head" > ${BUILD_LOGS}/smoketested-rev
fi
