#!/usr/bin/python

import sys
import time
import libvirt

# We don't do much error checking here. Just let exceptions
# rise up and exit non-zero.

domain_name = sys.argv[1]

timeout = 0
if len(sys.argv) > 2:
    timeout = int(sys.argv[2])

conn = libvirt.openReadOnly(None)
domain = conn.lookupByName(domain_name)

addrs = domain.interfaceAddresses(libvirt.VIR_DOMAIN_INTERFACE_ADDRESSES_SRC_LEASE)
while len(addrs) == 0 and timeout > 0:
    time.sleep(1)
    timeout -= 1
    addrs = domain.interfaceAddresses(libvirt.VIR_DOMAIN_INTERFACE_ADDRESSES_SRC_LEASE)

# just pick the first addr of the first iface
iface = addrs.keys()[0]
print addrs[iface]['addrs'][0]['addr']
